# Generated by Django 3.1.5 on 2021-01-05 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', help_text='Your name', max_length=64, verbose_name='Name')),
                ('company', models.CharField(blank=True, default='', help_text='Your organization’s name', max_length=64, verbose_name='Company')),
                ('email', models.EmailField(blank=True, default='', error_messages={'invalid': 'Please enter a correctly formatted email address.'}, help_text='Your email address', max_length=255, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', help_text='If you wish to be contacted by phone, please ensure you enter the correct number here.', max_length=32, verbose_name='Phone')),
                ('comments', models.TextField(blank=True, default='', help_text='Please let us know what is on your mind.', verbose_name='Message')),
                ('contact_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='When this person completed the contact form.', verbose_name='contact date')),
                ('was_contacted', models.BooleanField(default=False, help_text='Check this if someone has already reached out to this person.', verbose_name='has been contacted?')),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes relating to contacting this person.', verbose_name='contact notes')),
                ('referer', models.CharField(blank=True, default='', help_text='This is the page the visitor was on before coming to the contact page.', max_length=2048, verbose_name='referring page')),
            ],
        ),
    ]
